shell tmux

# Everforest Hard
background #272e33
foreground #d3c6aa

selection_background #4c3743
selection_foreground #d3c6aa

cursor #a7c080
cursor_text_color #272e33

# normal
color0  #414b50
color1  #e67e80
color2  #a7c080
color3  #dbbc7f
color4  #7fbbb3
color5  #d699b6
color6  #83c092
color7  #d3c6aa

# bright
color8  #475258
color9  #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #d3c6aa
